#!/usr/bin/env bash
set -euo pipefail

# ensure HOME and USER are set (may be unset in Lima environments)
HOME="${HOME:-$(eval echo ~)}"
USER="${USER:-$(whoami)}"
export HOME USER

get_path() {
  local file="$1"
  if [[ "${file:0:1}" == "/" ]]; then
    echo "$file"
  else
    echo "$HOME/$file"
  fi
}

is_non_linked_file() {
  local file="$1"
  [[ -e "$file" && ! -L "$file" ]]
}

ensure_exists() {
  local path
  path=$(get_path "$1")
  mkdir -p "$path"
}

link_file() {
  local src dest
  src=$(get_path "$1")
  dest=$(get_path "$2")
  if is_non_linked_file "$dest"; then
    echo "File already exists: $dest -- aborting installation" >&2
    exit 1
  fi
  rm -f "$dest"
  ln -s "$src" "$dest"
  echo "linked $src to $dest"
}

copy_file() {
  local src dest
  src=$(get_path "$1")
  if [[ ! -e "$src" ]]; then
    echo "not copying $src - file doesn't exist"
    return
  fi
  dest=$(get_path "$2")
  if [[ ! -e "$dest" ]]; then
    cp "$src" "$dest"
  fi
  echo "copied $src to $dest"
}

merge_files() {
  local user="$1"
  local src dest
  src=$(get_path "$2")
  dest=$(get_path "$3")
  local header="#generated by dohdots lima-install"
  local backup_line=""
  if is_non_linked_file "$dest"; then
    local destbackup="${dest}.backup-by-dohdots-install-$(date '+%F:%T')"
    echo "moving $dest to $destbackup"
    mv "$dest" "$destbackup"
    backup_line="#previous file exists at: $destbackup"
  fi
  local userfile="${src}.${user}"
  {
    echo "$header"
    [[ -n "$backup_line" ]] && echo "$backup_line"
    cat "$src"
    [[ -f "$userfile" ]] && cat "$userfile"
  } > "$dest"
}

getuser() {
  local user="$USER"
  case "$user" in
    kmason)  user="kem" ;;
    mmason)  user="makani" ;;
    tlarson) user="trent" ;;
  esac
  echo "$user"
}

get_dohdots() {
  local dohdots_path
  dohdots_path=$(get_path "src/dohdots")
  if [[ ! -e "$dohdots_path" ]]; then
    echo "gitting dohdots from github"
    ensure_exists "src"
    git clone https://github.com/atpsoft/dohdots.git "$HOME/src/dohdots"
  else
    echo "updating dohdots from github"
    (cd "$HOME/src/dohdots" && git pull)
  fi
}

link_files() {
  local shell_name="${1:-bash}"
  shell_name="${shell_name,,}"
  shell_name="${shell_name// /}"

  if [[ "$shell_name" != "bash" && "$shell_name" != "zsh" ]]; then
    echo "please enter a valid shell name: bash or zsh"
    exit 1
  fi

  echo "linking $shell_name"
  local user
  user=$(getuser)
  echo "linking dotfiles for user: $user"

  link_file "src/dohdots/git/gitignore" ".gitignore"

  if [[ "$shell_name" == "bash" ]]; then
    link_file "src/dohdots/bash/bash_profile" ".bash_profile"
  elif [[ "$shell_name" == "zsh" ]]; then
    link_file "src/dohdots/zsh/zprofile" ".zprofile"
  fi

  local user_rc
  user_rc=$(get_path "src/dohdots/$shell_name/${shell_name}rc.$user")
  if [[ -e "$user_rc" ]]; then
    link_file "src/dohdots/$shell_name/${shell_name}rc.$user" ".${shell_name}rc.user"
  fi

  link_file "src/dohdots/$shell_name/${shell_name}rc" ".${shell_name}rc"
  link_file "src/dohdots/emacs/emacs" ".emacs"
  link_file "src/dohdots/emacs/emacs.d" ".emacs.d"

  local user_emacs
  user_emacs=$(get_path "src/dohdots/emacs/emacs.$user")
  if [[ -e "$user_emacs" ]]; then
    link_file "src/dohdots/emacs/emacs.$user" ".emacs.user"
  fi

  link_file "src/dohdots/git/gitconfig" ".gitconfig"

  local user_gitconfig
  user_gitconfig=$(get_path "src/dohdots/git/gitconfig.$user")
  if [[ -e "$user_gitconfig" ]]; then
    link_file "src/dohdots/git/gitconfig.$user" ".gitconfig.user"
  fi
}

get_dohdots
link_files "${1:-}"
