(defconst emacs-ldquo #x5397c)
(defconst emacs-rdquo #x5397d)
(defconst emacs-lsquo #x53978)
(defconst emacs-rsquo #x53979)
(defconst emacs-quot  #x0022)
(defconst emacs-apos  #x0027)
(defun replace-bad-chars()
	(interactive)
	(let ((curpos (point)))
		(beginning-of-buffer)
		(replace-string (make-string 1 emacs-rdquo) "\"")
		(beginning-of-buffer)
		(replace-string (make-string 1 emacs-ldquo) "\"")
		(beginning-of-buffer)
		(replace-string (make-string 1 emacs-lsquo) "'")
		(beginning-of-buffer)
		(replace-string (make-string 1 emacs-rsquo) "'")
		(beginning-of-buffer)
		(replace-string (make-string 1 emacs-apos) "'")
		(goto-char curpos)
	)
)
