;; will insert spaces before comma number 'commanum' on the current line, until that comma is positioned at column 'column'
(defun csv-lineup-to-char (&optional commanumparam columnparam)
	(interactive)
	(let* ((commanum (or commanumparam (read-number "Enter the comma number to indent: ")))
				 (column (or columnparam (read-number "Enter the column # to indent to: "))))
		(message "comma num: %d column: %d" commanum column)
		(move-beginning-of-line nil)
		(while (> commanum 0)
			(search-forward ",")
			(setq commanum (1- commanum)))
			(backward-char)
		(let ((spaces-to-add (- column (current-column))))
			(re-search-backward ",")
			(forward-char)
			(if (< spaces-to-add 0)
					(error "unable to add spaces: %d" spaces-to-add))
			(while (> spaces-to-add 0)
				(insert-string " ")
				(setq spaces-to-add (1- spaces-to-add))
				)
			)
		)
)

