#!/bin/zsh
umask 077
max_lines=50000

linecount=$(wc -l < ~/.zsh_history)

if (($linecount > $max_lines)); then
        prune_lines=$(($linecount - $max_lines))
        head -$prune_lines ~/.zsh_history >> ~/.zsh_history.archive \
               && sed -e "1,${prune_lines}d"  ~/.zsh_history > ~/.zsh_history.tmp$$ \
               && mv ~/.zsh_history.tmp$$ ~/.zsh_history
fi
